# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `activerecord-enhancedsqlite3-adapter` gem.
# Please instead update this file by running `bin/tapioca gem activerecord-enhancedsqlite3-adapter`.

# see: https://github.com/rails/rails/pull/49346
#
# source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/version.rb#1
module EnhancedSQLite3
  # source://activerecord-enhancedsqlite3-adapter//lib/activerecord-enhancedsqlite3-adapter.rb#8
  def isolate_connection_pools=(val); end

  class << self
    # source://activerecord-enhancedsqlite3-adapter//lib/activerecord-enhancedsqlite3-adapter.rb#8
    def isolate_connection_pools=(val); end

    # @return [Boolean]
    #
    # source://activerecord-enhancedsqlite3-adapter//lib/activerecord-enhancedsqlite3-adapter.rb#11
    def isolate_connection_pools?; end
  end
end

# source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/adapter.rb#12
module EnhancedSQLite3::Adapter
  # Setup the Rails SQLite3 adapter instance.
  #
  # extends  https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L90
  #
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/adapter.rb#16
  def initialize(*_arg0, &_arg1); end

  # Perform any necessary initialization upon the newly-established
  # connection settings, run queries to configure any application-global
  # "session" variables, etc.
  #
  # Implementations may assume this method will only be called while
  # holding @lock (or from #initialize).
  #
  # overrides https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L691
  #
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/adapter.rb#43
  def configure_connection; end

  # Patch the #log method to ensure that all log messages are tagged with the database connection name.
  #
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/adapter.rb#61
  def log(*_arg0, &_arg1); end

  # Patch the #transaction method to ensure that all transactions are sent to the writing role database connection pool.
  #
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/adapter.rb#54
  def transaction(*_arg0, &_arg1); end

  private

  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/adapter.rb#72
  def configure_busy_handler_timeout; end

  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/adapter.rb#130
  def configure_extensions; end

  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/adapter.rb#95
  def configure_pragmas; end
end

# source://activerecord-enhancedsqlite3-adapter//lib/activerecord-enhancedsqlite3-adapter.rb#6
class EnhancedSQLite3::Error < ::StandardError; end

# source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/railtie.rb#8
class EnhancedSQLite3::Railtie < ::Rails::Railtie; end

# source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/resolver.rb#4
class EnhancedSQLite3::Resolver < ::ActiveRecord::Middleware::DatabaseSelector::Resolver
  # @return [Boolean]
  #
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/resolver.rb#5
  def reading_request?(request); end
end

# source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_deferrable_constraints.rb#5
module EnhancedSQLite3::SupportsDeferrableConstraints
  class << self
    # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_deferrable_constraints.rb#6
    def apply!; end
  end
end

# source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_deferrable_constraints.rb#11
module EnhancedSQLite3::SupportsDeferrableConstraints::Adapter
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_deferrable_constraints.rb#54
  def add_foreign_key(from_table, to_table, **options); end

  # @raise [ArgumentError]
  #
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_deferrable_constraints.rb#90
  def assert_valid_deferrable(deferrable); end

  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_deferrable_constraints.rb#18
  def foreign_keys(table_name); end

  # @return [Boolean]
  #
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_deferrable_constraints.rb#12
  def supports_deferrable_constraints?; end

  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_deferrable_constraints.rb#68
  def table_structure_sql(table_name); end
end

# source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_deferrable_constraints.rb#17
EnhancedSQLite3::SupportsDeferrableConstraints::Adapter::DEFERRABLE_REGEX = T.let(T.unsafe(nil), Regexp)

# source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_deferrable_constraints.rb#16
EnhancedSQLite3::SupportsDeferrableConstraints::Adapter::FK_REGEX = T.let(T.unsafe(nil), Regexp)

# source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_deferrable_constraints.rb#97
module EnhancedSQLite3::SupportsDeferrableConstraints::SchemaCreation
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_deferrable_constraints.rb#98
  def visit_AddForeignKey(o); end

  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_deferrable_constraints.rb#104
  def visit_ForeignKeyDefinition(o); end
end

# source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#5
module EnhancedSQLite3::SupportsVirtualColumns
  class << self
    # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#6
    def apply!; end
  end
end

# source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#14
module EnhancedSQLite3::SupportsVirtualColumns::Adapter
  # @raise [ActiveRecord::StatementInvalid]
  #
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#47
  def column_definitions(table_name); end

  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#117
  def extract_generated_type(field); end

  # @return [Boolean]
  #
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#58
  def invalid_alter_table_type?(type, options); end

  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#19
  def new_column_from_field(table_name, field, definitions); end

  # @return [Boolean]
  #
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#15
  def supports_virtual_columns?; end

  # @raise [ActiveRecord::StatementInvalid]
  #
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#47
  def table_structure(table_name); end

  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#66
  def table_structure_with_collation(table_name, basic_structure); end
end

# source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#65
EnhancedSQLite3::SupportsVirtualColumns::Adapter::GENERATED_ALWAYS_AS_REGEX = T.let(T.unsafe(nil), Regexp)

# source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#125
module EnhancedSQLite3::SupportsVirtualColumns::Column
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#126
  def initialize(*_arg0, auto_increment: T.unsafe(nil), rowid: T.unsafe(nil), generated_type: T.unsafe(nil), **_arg4); end

  # @return [Boolean]
  #
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#139
  def has_default?; end

  # @return [Boolean]
  #
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#131
  def virtual?; end

  # @return [Boolean]
  #
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#135
  def virtual_stored?; end
end

# source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#144
module EnhancedSQLite3::SupportsVirtualColumns::SchemaCreation
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#145
  def add_column_options!(sql, options); end
end

# source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#178
module EnhancedSQLite3::SupportsVirtualColumns::SchemaDumper
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#191
  def extract_expression_for_virtual_column(column); end

  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#179
  def prepare_column_options(column); end
end

# source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#163
module EnhancedSQLite3::SupportsVirtualColumns::TableDefinition
  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#164
  def new_column_definition(name, type, **options); end

  # source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/supports_virtual_columns.rb#173
  def valid_column_definition_options; end
end

# source://activerecord-enhancedsqlite3-adapter//lib/enhanced_sqlite3/version.rb#2
EnhancedSQLite3::VERSION = T.let(T.unsafe(nil), String)
