# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `syntax_tree-rbs` gem.
# Please instead update this file by running `bin/tapioca gem syntax_tree-rbs`.

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#36
module RBS
  class << self
    # source://rbs/3.4.4/lib/rbs.rb#67
    def logger; end

    # source://rbs/3.4.4/lib/rbs.rb#64
    def logger_level; end

    # source://rbs/3.4.4/lib/rbs.rb#76
    def logger_level=(level); end

    # source://rbs/3.4.4/lib/rbs.rb#65
    def logger_output; end

    # source://rbs/3.4.4/lib/rbs.rb#71
    def logger_output=(val); end

    # source://rbs/3.4.4/lib/rbs.rb#81
    def print_warning; end
  end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#45
module RBS::AST; end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#46
module RBS::AST::Declarations; end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#47
class RBS::AST::Declarations::Base
  include ::SyntaxTree::RBS::Entrypoints
end

# class Foo end
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#52
class RBS::AST::Declarations::Class < ::RBS::AST::Declarations::Base
  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#97
  def initialize(name:, type_params:, super_class:, members:, annotations:, location:, comment:); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#107
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#53
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#93
  def annotations; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#95
  def comment; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#107
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#117
  def hash; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#94
  def location; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#91
  def members; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#89
  def name; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#92
  def super_class; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#121
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#90
  def type_params; end
end

# Foo: String
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#59
class RBS::AST::Declarations::Constant < ::RBS::AST::Declarations::Base
  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#317
  def initialize(name:, type:, location:, comment:); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#324
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#60
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#315
  def comment; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#324
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#332
  def hash; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#314
  def location; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#312
  def name; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#336
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#313
  def type; end
end

# $foo: String
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#66
class RBS::AST::Declarations::Global < ::RBS::AST::Declarations::Base
  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#353
  def initialize(name:, type:, location:, comment:); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#360
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#67
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#351
  def comment; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#360
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#368
  def hash; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#350
  def location; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#348
  def name; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#372
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#349
  def type; end
end

# interface _Foo end
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#73
class RBS::AST::Declarations::Interface < ::RBS::AST::Declarations::Base
  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#233
  def initialize(name:, type_params:, members:, annotations:, location:, comment:); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#242
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#74
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#227
  def annotations; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#229
  def comment; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#242
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#251
  def hash; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#228
  def location; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#226
  def members; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#224
  def name; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#255
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#225
  def type_params; end
end

# module Foo end
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#80
class RBS::AST::Declarations::Module < ::RBS::AST::Declarations::Base
  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#185
  def initialize(name:, type_params:, members:, self_types:, annotations:, location:, comment:); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#195
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#81
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#181
  def annotations; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#183
  def comment; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#195
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#205
  def hash; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#180
  def location; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#179
  def members; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#177
  def name; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#182
  def self_types; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#209
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#178
  def type_params; end
end

# type foo = String
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#87
class RBS::AST::Declarations::TypeAlias < ::RBS::AST::Declarations::Base
  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#276
  def initialize(name:, type_params:, type:, annotations:, location:, comment:); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#285
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#88
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#272
  def annotations; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#274
  def comment; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#285
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#294
  def hash; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#273
  def location; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#269
  def name; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#298
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#271
  def type; end

  # source://rbs/3.4.4/lib/rbs/ast/declarations.rb#270
  def type_params; end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#94
module RBS::AST::Members; end

# alias foo bar
# alias self.foo self.bar
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#101
class RBS::AST::Members::Alias < ::RBS::AST::Members::Base
  # source://rbs/3.4.4/lib/rbs/ast/members.rb#405
  def initialize(new_name:, old_name:, kind:, annotations:, location:, comment:); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#414
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#102
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#401
  def annotations; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#403
  def comment; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#414
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#423
  def hash; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#439
  def instance?; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#400
  def kind; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#402
  def location; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#398
  def new_name; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#399
  def old_name; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#443
  def singleton?; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#427
  def to_json(state = T.unsafe(nil)); end
end

# attr_accessor foo: Foo
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#108
class RBS::AST::Members::AttrAccessor < ::RBS::AST::Members::Base
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#109
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#330
  def to_json(state = T.unsafe(nil)); end
end

# attr_reader foo: Foo
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#115
class RBS::AST::Members::AttrReader < ::RBS::AST::Members::Base
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#116
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#312
  def to_json(state = T.unsafe(nil)); end
end

# attr_writer foo: Foo
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#122
class RBS::AST::Members::AttrWriter < ::RBS::AST::Members::Base
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#123
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#348
  def to_json(state = T.unsafe(nil)); end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#95
class RBS::AST::Members::Base
  include ::SyntaxTree::RBS::Entrypoints
end

# self.@foo: String
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#129
class RBS::AST::Members::ClassInstanceVariable < ::RBS::AST::Members::Base
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#130
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#160
  def to_json(state = T.unsafe(nil)); end
end

# @@foo: String
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#136
class RBS::AST::Members::ClassVariable < ::RBS::AST::Members::Base
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#137
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#174
  def to_json(state = T.unsafe(nil)); end
end

# extend Foo
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#143
class RBS::AST::Members::Extend < ::RBS::AST::Members::Base
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#144
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#231
  def to_json(state = T.unsafe(nil)); end
end

# include Foo
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#150
class RBS::AST::Members::Include < ::RBS::AST::Members::Base
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#151
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#216
  def to_json(state = T.unsafe(nil)); end
end

# @foo: String
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#157
class RBS::AST::Members::InstanceVariable < ::RBS::AST::Members::Base
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#158
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#146
  def to_json(state = T.unsafe(nil)); end
end

# def t: (T t) -> void
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#164
class RBS::AST::Members::MethodDefinition < ::RBS::AST::Members::Base
  # source://rbs/3.4.4/lib/rbs/ast/members.rb#53
  def initialize(name:, kind:, overloads:, annotations:, location:, comment:, overloading:, visibility:); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#64
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#165
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#47
  def annotations; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#49
  def comment; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#64
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#75
  def hash; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#79
  def instance?; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#45
  def kind; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#48
  def location; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#44
  def name; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#50
  def overloading; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#87
  def overloading?; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#46
  def overloads; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#83
  def singleton?; end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#104
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#91
  def update(name: T.unsafe(nil), kind: T.unsafe(nil), overloads: T.unsafe(nil), annotations: T.unsafe(nil), location: T.unsafe(nil), comment: T.unsafe(nil), overloading: T.unsafe(nil), visibility: T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#51
  def visibility; end
end

# prepend Foo
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#171
class RBS::AST::Members::Prepend < ::RBS::AST::Members::Base
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#172
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#246
  def to_json(state = T.unsafe(nil)); end
end

# private
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#178
class RBS::AST::Members::Private < ::RBS::AST::Members::Base
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#179
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#392
  def to_json(state = T.unsafe(nil)); end
end

# public
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#185
class RBS::AST::Members::Public < ::RBS::AST::Members::Base
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#186
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/ast/members.rb#384
  def to_json(state = T.unsafe(nil)); end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#37
class RBS::TypeName
  include ::SyntaxTree::RBS::Entrypoints

  # source://rbs/3.4.4/lib/rbs/type_name.rb#9
  def initialize(namespace:, name:); end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#79
  def +(other); end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#25
  def ==(other); end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#55
  def absolute!; end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#59
  def absolute?; end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#40
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#51
  def alias?; end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#47
  def class?; end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#25
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#31
  def hash; end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#67
  def interface?; end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#7
  def kind; end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#6
  def name; end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#5
  def namespace; end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#63
  def relative!; end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#75
  def split; end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#39
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#43
  def to_namespace; end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#35
  def to_s; end

  # source://rbs/3.4.4/lib/rbs/type_name.rb#71
  def with_prefix(namespace); end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#193
module RBS::Types; end

# Foo
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#195
class RBS::Types::Alias
  include ::SyntaxTree::RBS::Entrypoints

  # source://rbs/3.4.4/lib/rbs/types.rb#399
  def initialize(name:, args:, location:); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#198
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/types.rb#395
  def location; end

  # source://rbs/3.4.4/lib/rbs/types.rb#421
  def map_type(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#413
  def map_type_name(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#409
  def sub(s); end

  # source://rbs/3.4.4/lib/rbs/types.rb#405
  def to_json(state = T.unsafe(nil)); end
end

module RBS::Types::Bases; end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#204
class RBS::Types::Bases::Any < ::RBS::Types::Bases::Base
  include ::SyntaxTree::RBS::Entrypoints

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#207
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/types.rb#110
  def to_s(level = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#114
  def todo!; end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#213
class RBS::Types::Bases::Bool < ::RBS::Types::Bases::Base
  include ::SyntaxTree::RBS::Entrypoints

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#216
  def accept(visitor); end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#222
class RBS::Types::Bases::Bottom < ::RBS::Types::Bases::Base
  include ::SyntaxTree::RBS::Entrypoints

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#225
  def accept(visitor); end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#231
class RBS::Types::Bases::Class < ::RBS::Types::Bases::Base
  include ::SyntaxTree::RBS::Entrypoints

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#234
  def accept(visitor); end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#240
class RBS::Types::Bases::Instance < ::RBS::Types::Bases::Base
  include ::SyntaxTree::RBS::Entrypoints

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#243
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/types.rb#124
  def sub(s); end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#249
class RBS::Types::Bases::Nil < ::RBS::Types::Bases::Base
  include ::SyntaxTree::RBS::Entrypoints

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#252
  def accept(visitor); end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#258
class RBS::Types::Bases::Self < ::RBS::Types::Bases::Base
  include ::SyntaxTree::RBS::Entrypoints

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#261
  def accept(visitor); end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#267
class RBS::Types::Bases::Top < ::RBS::Types::Bases::Base
  include ::SyntaxTree::RBS::Entrypoints

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#270
  def accept(visitor); end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#276
class RBS::Types::Bases::Void < ::RBS::Types::Bases::Base
  include ::SyntaxTree::RBS::Entrypoints

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#279
  def accept(visitor); end
end

# Foo
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#285
class RBS::Types::ClassInstance
  include ::SyntaxTree::RBS::Entrypoints

  # source://rbs/3.4.4/lib/rbs/types.rb#357
  def initialize(name:, args:, location:); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#288
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/types.rb#353
  def location; end

  # source://rbs/3.4.4/lib/rbs/types.rb#381
  def map_type(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#373
  def map_type_name(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#367
  def sub(s); end

  # source://rbs/3.4.4/lib/rbs/types.rb#363
  def to_json(state = T.unsafe(nil)); end
end

# singleton(Foo)
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#294
class RBS::Types::ClassSingleton
  include ::SyntaxTree::RBS::Entrypoints

  # source://rbs/3.4.4/lib/rbs/types.rb#204
  def initialize(name:, location:); end

  # source://rbs/3.4.4/lib/rbs/types.rb#209
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#297
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/types.rb#209
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/types.rb#243
  def has_classish_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#239
  def has_self_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#215
  def hash; end

  # source://rbs/3.4.4/lib/rbs/types.rb#202
  def location; end

  # source://rbs/3.4.4/lib/rbs/types.rb#232
  def map_type_name; end

  # source://rbs/3.4.4/lib/rbs/types.rb#201
  def name; end

  # source://rbs/3.4.4/lib/rbs/types.rb#222
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#226
  def to_s(level = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#247
  def with_nonreturn_void?; end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#303
class RBS::Types::Function::Param
  include ::SyntaxTree::RBS::Entrypoints

  # source://rbs/3.4.4/lib/rbs/types.rb#856
  def initialize(type:, name:, location: T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#862
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#306
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/types.rb#862
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/types.rb#868
  def hash; end

  # source://rbs/3.4.4/lib/rbs/types.rb#854
  def location; end

  # source://rbs/3.4.4/lib/rbs/types.rb#872
  def map_type(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#853
  def name; end

  # source://rbs/3.4.4/lib/rbs/types.rb#880
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#884
  def to_s; end

  # source://rbs/3.4.4/lib/rbs/types.rb#852
  def type; end
end

# _Foo
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#312
class RBS::Types::Interface
  include ::SyntaxTree::RBS::Entrypoints

  # source://rbs/3.4.4/lib/rbs/types.rb#315
  def initialize(name:, args:, location:); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#315
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/types.rb#311
  def location; end

  # source://rbs/3.4.4/lib/rbs/types.rb#339
  def map_type(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#331
  def map_type_name(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#325
  def sub(s); end

  # source://rbs/3.4.4/lib/rbs/types.rb#321
  def to_json(state = T.unsafe(nil)); end
end

# foo & bar
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#321
class RBS::Types::Intersection
  include ::SyntaxTree::RBS::Entrypoints

  # source://rbs/3.4.4/lib/rbs/types.rb#773
  def initialize(types:, location:); end

  # source://rbs/3.4.4/lib/rbs/types.rb#778
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#324
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/types.rb#814
  def each_type(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#778
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/types.rb#788
  def free_variables(set = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#841
  def has_classish_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#837
  def has_self_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#784
  def hash; end

  # source://rbs/3.4.4/lib/rbs/types.rb#771
  def location; end

  # source://rbs/3.4.4/lib/rbs/types.rb#822
  def map_type(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#830
  def map_type_name(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#800
  def sub(s); end

  # source://rbs/3.4.4/lib/rbs/types.rb#796
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#805
  def to_s(level = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#770
  def types; end

  # source://rbs/3.4.4/lib/rbs/types.rb#845
  def with_nonreturn_void?; end
end

# 1
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#330
class RBS::Types::Literal
  include ::SyntaxTree::RBS::Entrypoints

  # source://rbs/3.4.4/lib/rbs/types.rb#1363
  def initialize(literal:, location:); end

  # source://rbs/3.4.4/lib/rbs/types.rb#1368
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#333
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/types.rb#1368
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/types.rb#1395
  def has_classish_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#1391
  def has_self_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#1374
  def hash; end

  # source://rbs/3.4.4/lib/rbs/types.rb#1360
  def literal; end

  # source://rbs/3.4.4/lib/rbs/types.rb#1361
  def location; end

  # source://rbs/3.4.4/lib/rbs/types.rb#1383
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#1387
  def to_s(level = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#1399
  def with_nonreturn_void?; end

  class << self
    # source://rbs/3.4.4/lib/rbs/types.rb#1419
    def unescape_string(string, is_double_quote); end
  end
end

# foo?
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#339
class RBS::Types::Optional
  include ::SyntaxTree::RBS::Entrypoints

  # source://rbs/3.4.4/lib/rbs/types.rb#609
  def initialize(type:, location:); end

  # source://rbs/3.4.4/lib/rbs/types.rb#614
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#342
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/types.rb#650
  def each_type; end

  # source://rbs/3.4.4/lib/rbs/types.rb#614
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/types.rb#624
  def free_variables(set = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#680
  def has_classish_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#676
  def has_self_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#620
  def hash; end

  # source://rbs/3.4.4/lib/rbs/types.rb#607
  def location; end

  # source://rbs/3.4.4/lib/rbs/types.rb#665
  def map_type(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#658
  def map_type_name(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#632
  def sub(s); end

  # source://rbs/3.4.4/lib/rbs/types.rb#628
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#636
  def to_s(level = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#606
  def type; end

  # source://rbs/3.4.4/lib/rbs/types.rb#684
  def with_nonreturn_void?; end
end

# ^-> void
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#348
class RBS::Types::Proc
  include ::SyntaxTree::RBS::Entrypoints

  # source://rbs/3.4.4/lib/rbs/types.rb#1245
  def initialize(location:, type:, block:, self_type: T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#1252
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#351
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/types.rb#1241
  def block; end

  # source://rbs/3.4.4/lib/rbs/types.rb#1304
  def each_type(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#1252
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/types.rb#1262
  def free_variables(set = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#1342
  def has_classish_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#1338
  def has_self_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#1258
  def hash; end

  # source://rbs/3.4.4/lib/rbs/types.rb#1243
  def location; end

  # source://rbs/3.4.4/lib/rbs/types.rb#1325
  def map_type(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#1316
  def map_type_name(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#1242
  def self_type; end

  # source://rbs/3.4.4/lib/rbs/types.rb#1279
  def sub(s); end

  # source://rbs/3.4.4/lib/rbs/types.rb#1269
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#1288
  def to_s(level = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#1240
  def type; end

  # source://rbs/3.4.4/lib/rbs/types.rb#1346
  def with_nonreturn_void?; end
end

# { foo: bar }
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#357
class RBS::Types::Record
  include ::SyntaxTree::RBS::Entrypoints

  # source://rbs/3.4.4/lib/rbs/types.rb#521
  def initialize(fields:, location:); end

  # source://rbs/3.4.4/lib/rbs/types.rb#526
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#360
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/types.rb#566
  def each_type(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#526
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/types.rb#518
  def fields; end

  # source://rbs/3.4.4/lib/rbs/types.rb#536
  def free_variables(set = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#596
  def has_classish_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#592
  def has_self_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#532
  def hash; end

  # source://rbs/3.4.4/lib/rbs/types.rb#519
  def location; end

  # source://rbs/3.4.4/lib/rbs/types.rb#581
  def map_type(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#574
  def map_type_name(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#548
  def sub(s); end

  # source://rbs/3.4.4/lib/rbs/types.rb#544
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#553
  def to_s(level = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#600
  def with_nonreturn_void?; end
end

# [foo, bar]
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#366
class RBS::Types::Tuple
  include ::SyntaxTree::RBS::Entrypoints

  # source://rbs/3.4.4/lib/rbs/types.rb#438
  def initialize(types:, location:); end

  # source://rbs/3.4.4/lib/rbs/types.rb#443
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#369
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/types.rb#478
  def each_type(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#443
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/types.rb#453
  def free_variables(set = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#508
  def has_classish_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#504
  def has_self_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#449
  def hash; end

  # source://rbs/3.4.4/lib/rbs/types.rb#436
  def location; end

  # source://rbs/3.4.4/lib/rbs/types.rb#493
  def map_type(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#486
  def map_type_name(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#465
  def sub(s); end

  # source://rbs/3.4.4/lib/rbs/types.rb#461
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#470
  def to_s(level = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#435
  def types; end

  # source://rbs/3.4.4/lib/rbs/types.rb#512
  def with_nonreturn_void?; end
end

# foo | bar
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#375
class RBS::Types::Union
  include ::SyntaxTree::RBS::Entrypoints

  # source://rbs/3.4.4/lib/rbs/types.rb#693
  def initialize(types:, location:); end

  # source://rbs/3.4.4/lib/rbs/types.rb#698
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#378
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/types.rb#733
  def each_type(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#698
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/types.rb#708
  def free_variables(set = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#760
  def has_classish_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#756
  def has_self_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#704
  def hash; end

  # source://rbs/3.4.4/lib/rbs/types.rb#691
  def location; end

  # source://rbs/3.4.4/lib/rbs/types.rb#741
  def map_type(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#749
  def map_type_name(&block); end

  # source://rbs/3.4.4/lib/rbs/types.rb#720
  def sub(s); end

  # source://rbs/3.4.4/lib/rbs/types.rb#716
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#725
  def to_s(level = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#690
  def types; end

  # source://rbs/3.4.4/lib/rbs/types.rb#764
  def with_nonreturn_void?; end
end

# foo
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#384
class RBS::Types::Variable
  include ::SyntaxTree::RBS::Entrypoints

  # source://rbs/3.4.4/lib/rbs/types.rb#137
  def initialize(name:, location:); end

  # source://rbs/3.4.4/lib/rbs/types.rb#142
  def ==(other); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#387
  def accept(visitor); end

  # source://rbs/3.4.4/lib/rbs/types.rb#142
  def eql?(other); end

  # source://rbs/3.4.4/lib/rbs/types.rb#152
  def free_variables(set = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#191
  def has_classish_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#187
  def has_self_type?; end

  # source://rbs/3.4.4/lib/rbs/types.rb#148
  def hash; end

  # source://rbs/3.4.4/lib/rbs/types.rb#133
  def location; end

  # source://rbs/3.4.4/lib/rbs/types.rb#132
  def name; end

  # source://rbs/3.4.4/lib/rbs/types.rb#162
  def sub(s); end

  # source://rbs/3.4.4/lib/rbs/types.rb#158
  def to_json(state = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#181
  def to_s(level = T.unsafe(nil)); end

  # source://rbs/3.4.4/lib/rbs/types.rb#195
  def with_nonreturn_void?; end

  class << self
    # source://rbs/3.4.4/lib/rbs/types.rb#166
    def build(v); end

    # source://rbs/3.4.4/lib/rbs/types.rb#176
    def fresh(v = T.unsafe(nil)); end
  end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs.rb#7
module SyntaxTree
  class << self
    # source://syntax_tree/6.2.0/lib/syntax_tree.rb#60
    def format(source, maxwidth = T.unsafe(nil), base_indentation = T.unsafe(nil), options: T.unsafe(nil)); end

    # source://syntax_tree/6.2.0/lib/syntax_tree.rb#76
    def format_file(filepath, maxwidth = T.unsafe(nil), base_indentation = T.unsafe(nil), options: T.unsafe(nil)); end

    # source://syntax_tree/6.2.0/lib/syntax_tree.rb#86
    def format_node(source, node, maxwidth = T.unsafe(nil), base_indentation = T.unsafe(nil), options: T.unsafe(nil)); end

    # source://syntax_tree/6.2.0/lib/syntax_tree.rb#103
    def index(source); end

    # source://syntax_tree/6.2.0/lib/syntax_tree.rb#110
    def index_file(filepath); end

    # source://syntax_tree/6.2.0/lib/syntax_tree.rb#115
    def mutation; end

    # source://syntax_tree/6.2.0/lib/syntax_tree.rb#122
    def parse(source); end

    # source://syntax_tree/6.2.0/lib/syntax_tree.rb#129
    def parse_file(filepath); end

    # source://syntax_tree/6.2.0/lib/syntax_tree.rb#135
    def read(filepath); end

    # source://syntax_tree/6.2.0/lib/syntax_tree.rb#150
    def register_handler(extension, handler); end

    # source://syntax_tree/6.2.0/lib/syntax_tree.rb#156
    def search(source, query, &block); end

    # source://syntax_tree/6.2.0/lib/syntax_tree.rb#165
    def search_file(filepath, query, &block); end
  end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs.rb#8
module SyntaxTree::RBS
  class << self
    # source://syntax_tree-rbs//lib/syntax_tree/rbs.rb#44
    def format(source, maxwidth = T.unsafe(nil)); end

    # source://syntax_tree-rbs//lib/syntax_tree/rbs.rb#52
    def parse(source); end

    # source://syntax_tree-rbs//lib/syntax_tree/rbs.rb#57
    def read(filepath); end
  end
end

# These are the methods that are going to be defined on each node of the
# AST. They each will create a visitor and enter into the visitor's walking
# algorithm.
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#8
module SyntaxTree::RBS::Entrypoints
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#9
  def format(q); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#13
  def pretty_print(q); end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#5
class SyntaxTree::RBS::Format < ::SyntaxTree::RBS::Visitor
  # @return [Format] a new instance of Format
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#8
  def initialize(q); end

  # Returns the value of attribute q.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#6
  def q; end

  # Visit a RBS::AST::Members::Alias node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#17
  def visit_alias(node); end

  # Visit a RBS::Types::Alias node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#35
  def visit_alias_type(node); end

  # Visit a RBS::Types::Bases::Any node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#12
  def visit_any_type(node); end

  # Visit a RBS::AST::Members::AttrAccessor node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#43
  def visit_attr_accessor_member(node); end

  # Visit a RBS::AST::Members::AttrReader node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#50
  def visit_attr_reader_member(node); end

  # Visit a RBS::AST::Members::AttrWriter node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#57
  def visit_attr_writer_member(node); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#12
  def visit_base_type(node); end

  # Visit a RBS::Types::Bases::Bool node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#12
  def visit_bool_type(node); end

  # Visit a RBS::Types::Bases::Bottom node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#12
  def visit_bottom_type(node); end

  # Visit a RBS::AST::Declarations::Class node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#70
  def visit_class_declaration(node); end

  # Visit a RBS::Types::ClassInstance node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#90
  def visit_class_instance_type(node); end

  # Visit a RBS::AST::Members::ClassInstanceVariable node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#95
  def visit_class_instance_variable_member(node); end

  # Visit a RBS::Types::ClassSingleton node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#107
  def visit_class_singleton_type(node); end

  # Visit a RBS::Types::Bases::Class node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#12
  def visit_class_type(node); end

  # Visit a RBS::AST::Members::ClassVariable node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#117
  def visit_class_variable_member(node); end

  # Visit a RBS::AST::Declarations::Constant node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#128
  def visit_constant_declaration(node); end

  # Visit a RBS::AST::Members::Extend node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#139
  def visit_extend_member(node); end

  # Visit a RBS::Types::Function::Param node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#150
  def visit_function_param_type(node); end

  # Visit a RBS::AST::Declarations::Global node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#165
  def visit_global_declaration(node); end

  # Visit a RBS::AST::Members::Include node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#176
  def visit_include_member(node); end

  # Visit a RBS::Types::Bases::Instance node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#12
  def visit_instance_type(node); end

  # Visit a RBS::AST::Members::InstanceVariable node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#190
  def visit_instance_variable_member(node); end

  # Visit a RBS::AST::Declarations::Interface node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#201
  def visit_interface_declaration(node); end

  # Visit a RBS::Types::Interface node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#215
  def visit_interface_type(node); end

  # Visit a RBS::Types::Intersection node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#220
  def visit_intersection_type(node); end

  # Visit a RBS::Types::Literal node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#237
  def visit_literal_type(node); end

  # Visit a RBS::AST::Members::MethodDefinition node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#259
  def visit_method_definition_member(node); end

  # Visit a RBS::AST::Declarations::Module node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#312
  def visit_module_declaration(node); end

  # Visit a RBS::Types::Bases::Nil node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#12
  def visit_nil_type(node); end

  # Visit a RBS::Types::Optional node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#337
  def visit_optional_type(node); end

  # Visit a RBS::AST::Members::Prepend node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#343
  def visit_prepend_member(node); end

  # Visit a RBS::AST::Members::Private node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#354
  def visit_private_member(node); end

  # Visit a RBS::Types::Proc node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#359
  def visit_proc_type(node); end

  # Visit a RBS::AST::Members::Public node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#369
  def visit_public_member(node); end

  # Visit a RBS::Types::Record node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#374
  def visit_record_type(node); end

  # Visit a SyntaxTree::RBS::Root node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#401
  def visit_root(node); end

  # Visit a RBS::Types::Self node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#12
  def visit_self_type(node); end

  # Visit a RBS::Types::Top node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#12
  def visit_top_type(node); end

  # Visit a RBS::Types::Tuple node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#422
  def visit_tuple_type(node); end

  # Visit a RBS::AST::Declarations::TypeAlias node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#438
  def visit_type_alias(node); end

  # Visit a RBS::TypeName node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#456
  def visit_type_name(node); end

  # Visit a RBS::Types::Union node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#461
  def visit_union_type(node); end

  # Visit a RBS::Types::Variable node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#474
  def visit_variable_type(node); end

  # Visit a RBS::Types::Bases::Void node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#12
  def visit_void_type(node); end

  private

  # An annotation can be attached to many kinds of nodes, and should be
  # printed using %a{}.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#485
  def print_annotations(node); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#503
  def print_attribute(type, node); end

  # Comments come in as one whole string, so here we split it up into
  # multiple lines and then prefix it with the pound sign.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#525
  def print_comment(node); end

  # Nodes which have members will all flow their printing through this
  # class, which keeps track of
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#538
  def print_members(node); end

  # (T t) -> void
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#554
  def print_method_overload(node); end

  # (T t) -> void
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#559
  def print_method_signature(node); end

  # Certain nodes are names with optional arguments attached, as in
  # Array[A]. We handle all of that printing centralized here.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#658
  def print_name_and_args(node); end

  # Prints out the name of a class, interface, or module declaration.
  # Additionally loops through each type parameter if there are any and
  # print them out joined by commas. Checks for validation and variance.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/format.rb#673
  def print_name_and_type_params(node); end
end

# A slight extension to the default PrettierPrint formatter that keeps track
# of the source (so that it can be referenced by annotations if they need
# it) and keeps track of the level of intersections and unions so that
# parentheses can be forced if necessary.
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs.rb#21
class SyntaxTree::RBS::Formatter < ::PrettierPrint
  # @return [Formatter] a new instance of Formatter
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs.rb#24
  def initialize(source, *rest); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs.rb#30
  def force_parens; end

  # @return [Boolean]
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs.rb#38
  def force_parens?; end

  # Returns the value of attribute source.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs.rb#22
  def source; end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#5
class SyntaxTree::RBS::PrettyPrint < ::SyntaxTree::RBS::Visitor
  # @return [PrettyPrint] a new instance of PrettyPrint
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#8
  def initialize(q); end

  # Returns the value of attribute q.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#6
  def q; end

  # Visit a RBS::AST::Members::Alias node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#17
  def visit_alias(node); end

  # Visit a RBS::Types::Alias node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#28
  def visit_alias_type(node); end

  # Visit a RBS::Types::Bases::Any node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#12
  def visit_any_type(node); end

  # Visit a RBS::AST::Members::AttrAccessor node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#36
  def visit_attr_accessor_member(node); end

  # Visit a RBS::AST::Members::AttrReader node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#45
  def visit_attr_reader_member(node); end

  # Visit a RBS::AST::Members::AttrWriter node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#54
  def visit_attr_writer_member(node); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#12
  def visit_base_type(node); end

  # Visit a RBS::Types::Bases::Bool node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#12
  def visit_bool_type(node); end

  # Visit a RBS::Types::Bases::Bottom node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#12
  def visit_bottom_type(node); end

  # Visit a RBS::AST::Declarations::Class node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#69
  def visit_class_declaration(node); end

  # Visit a RBS::Types::ClassInstance node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#86
  def visit_class_instance_type(node); end

  # Visit a RBS::AST::Members::ClassInstanceVariable node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#91
  def visit_class_instance_variable_member(node); end

  # Visit a RBS::Types::ClassSingleton node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#99
  def visit_class_singleton_type(node); end

  # Visit a RBS::Types::Bases::Class node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#12
  def visit_class_type(node); end

  # Visit a RBS::AST::Members::ClassVariable node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#107
  def visit_class_variable_member(node); end

  # Visit a RBS::AST::Declarations::Constant node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#115
  def visit_constant_declaration(node); end

  # Visit a RBS::AST::Members::Extend node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#124
  def visit_extend_member(node); end

  # Visit a RBS::Types::Function::Param node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#133
  def visit_function_param_type(node); end

  # Visit a RBS::AST::Declarations::Global node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#141
  def visit_global_declaration(node); end

  # Visit a RBS::AST::Members::Include node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#150
  def visit_include_member(node); end

  # Visit a RBS::Types::Bases::Instance node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#12
  def visit_instance_type(node); end

  # Visit a RBS::AST::Members::InstanceVariable node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#162
  def visit_instance_variable_member(node); end

  # Visit a RBS::AST::Declarations::Interface node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#170
  def visit_interface_declaration(node); end

  # Visit a RBS::Types::Interface node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#180
  def visit_interface_type(node); end

  # Visit a RBS::Types::Intersection node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#185
  def visit_intersection_type(node); end

  # Visit a RBS::Types::Literal node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#190
  def visit_literal_type(node); end

  # Visit a RBS::AST::Members::MethodDefinition node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#195
  def visit_method_definition_member(node); end

  # Visit a RBS::AST::Declarations::Module node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#215
  def visit_module_declaration(node); end

  # Visit a RBS::Types::Bases::Nil node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#12
  def visit_nil_type(node); end

  # Visit a RBS::Types::Optional node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#239
  def visit_optional_type(node); end

  # Visit a RBS::AST::Members::Prepend node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#244
  def visit_prepend_member(node); end

  # Visit a RBS::AST::Members::Private node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#253
  def visit_private_member(node); end

  # Visit a RBS::Types::Proc node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#258
  def visit_proc_type(node); end

  # Visit a RBS::AST::Members::Public node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#263
  def visit_public_member(node); end

  # Visit a RBS::Types::Record node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#268
  def visit_record_type(node); end

  # Visit a SyntaxTree::RBS::Root node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#273
  def visit_root(node); end

  # Visit a RBS::Types::Self node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#12
  def visit_self_type(node); end

  # Visit a RBS::Types::Top node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#12
  def visit_top_type(node); end

  # Visit a RBS::Types::Tuple node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#284
  def visit_tuple_type(node); end

  # Visit a RBS::AST::Declarations::TypeAlias node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#289
  def visit_type_alias(node); end

  # Visit a RBS::TypeName node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#299
  def visit_type_name(node); end

  # Visit a RBS::Types::Union node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#307
  def visit_union_type(node); end

  # Visit a RBS::Types::Variable node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#312
  def visit_variable_type(node); end

  # Visit a RBS::Types::Bases::Void node.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#12
  def visit_void_type(node); end

  private

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#335
  def bool_field(name); end

  # -------------------------------------------------------------------------
  # Printing structure
  # -------------------------------------------------------------------------
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#325
  def group(name); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#340
  def pp_field(name, field); end

  # -------------------------------------------------------------------------
  # Printing certain kinds of nodes
  # -------------------------------------------------------------------------
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#356
  def print_annotations(node); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#370
  def print_attribute(node); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#397
  def print_comment(node); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#409
  def print_method_overload(node); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#413
  def print_method_signature(node); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#491
  def print_name_and_args(node); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#501
  def print_name_and_type_params(node); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/pretty_print.rb#346
  def visit_field(name, field); end
end

# This is the root node of the entire tree. It contains all of the top-level
# declarations within the file.
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#20
class SyntaxTree::RBS::Root
  include ::SyntaxTree::RBS::Entrypoints

  # @return [Root] a new instance of Root
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#25
  def initialize(declarations); end

  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#29
  def accept(visitor); end

  # Returns the value of attribute declarations.
  #
  # source://syntax_tree-rbs//lib/syntax_tree/rbs/entrypoints.rb#23
  def declarations; end
end

# source://syntax_tree-rbs//lib/syntax_tree/rbs/version.rb#5
SyntaxTree::RBS::VERSION = T.let(T.unsafe(nil), String)

# This is the parent class of any of the visitors that we define in this
# module. It is used to walk through the tree.
#
# source://syntax_tree-rbs//lib/syntax_tree/rbs.rb#11
class SyntaxTree::RBS::Visitor
  # source://syntax_tree-rbs//lib/syntax_tree/rbs.rb#12
  def visit(node); end
end
