# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `CreateRoboscoutQueryJob`.
# Please instead update this file by running `bin/tapioca dsl CreateRoboscoutQueryJob`.

class CreateRoboscoutQueryJob
  class << self
    sig { params(query: ::String).returns(String) }
    def perform_async(query); end

    sig { params(interval: T.any(DateTime, Time), query: ::String).returns(String) }
    def perform_at(interval, query); end

    sig { params(interval: Numeric, query: ::String).returns(String) }
    def perform_in(interval, query); end
  end
end
