# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `StartRoboscoutQueryJob`.
# Please instead update this file by running `bin/tapioca dsl StartRoboscoutQueryJob`.

class StartRoboscoutQueryJob
  class << self
    sig { params(query_id: ::Integer).returns(String) }
    def perform_async(query_id); end

    sig { params(interval: T.any(DateTime, Time), query_id: ::Integer).returns(String) }
    def perform_at(interval, query_id); end

    sig { params(interval: Numeric, query_id: ::Integer).returns(String) }
    def perform_in(interval, query_id); end
  end
end
