# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UpsertPersonJob`.
# Please instead update this file by running `bin/tapioca dsl UpsertPersonJob`.

class UpsertPersonJob
  class << self
    sig { params(person_id: ::Integer).returns(String) }
    def perform_async(person_id); end

    sig { params(interval: T.any(DateTime, Time), person_id: ::Integer).returns(String) }
    def perform_at(interval, person_id); end

    sig { params(interval: Numeric, person_id: ::Integer).returns(String) }
    def perform_in(interval, person_id); end
  end
end
